### ISSUE TITLE
Сборка проекта не работает из-за отсутствия .env.prod файла.

### ISSUE THREAD

**Issue by Danashi11** [CyberLympha/IS-Ontology#1]
Id: 1.

Шаги воспроизведения:
1) Открыть терминал.
2) Скачать проект на своё устройство с помощью команды git clone.
3) Перейти в папку проекта.
4) Запустить команду docker-compose up.

Актуальный результат:  Ошибка - файл .env.prod не найден.
Ожидаемый результат: Анализ конфига docker-compose.yml, скачивание нужных образов, монтаж файлов и папок, запуск контейнеров.

Окружение: Oracle VM VirtualBox, linux, ubuntu 22.04.4 LTS, 64-bit.

Критичность: Blocker.
Приоритет: High.

Приложения:
(https://github.com/CyberLympha/IS-Ontology/assets/115805485/bc42a7ec-7397-4855-929a-447e8dd0be01)
(https://github.com/CyberLympha/IS-Ontology/assets/115805485/abb94b85-d5cb-4166-a4b8-1ca65601edc8)
(https://github.com/CyberLympha/IS-Ontology/assets/115805485/2f55e806-63bf-4a47-a47f-4ef4cd2026ff)

Комментарий: Создаём пустой .env.prod файл для того чтобы обойти баг. В результате повторного запуска в дефолтной конфигурации nginx не поднимается, потому что 3000 порт в docker-compose закомментирован. Если его раскомментировать, то он поднимается, но далее возникает проблема с контейнером фронтенда. Также в docker-compose не указаны условия рестарта контейнеров, предполагаю, без него nginx поднимается раньше зависимых и сразу падает, не дождавшись их.

**Comment by yurichernyshov** [comment]
.env.prod file was added
